USE [master]
GO

/****** Object:  Database [QL_CONG_TAC_PHI]    Script Date: 3/5/2019 4:25:35 PM ******/
CREATE DATABASE [QL_CONG_TAC_PHI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QL_CONG_TAC_PHI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\QL_CONG_TAC_PHI.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QL_CONG_TAC_PHI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\QL_CONG_TAC_PHI_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QL_CONG_TAC_PHI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET ARITHABORT OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET  MULTI_USER 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QL_CONG_TAC_PHI] SET  READ_WRITE 
GO


